### ISSUE TITLE
__dirname is missing for modules

### ISSUE THREAD

**Issue by ReinWD** [vite-plugin/vite-plugin-commonjs#48]
### REPRODUCE STEPS
1. install module `prismarine-chunk`
2. call its loader function
3. receive a error saying "__dirname is not defined", thrown by module `minecraft-data`

here is an example written in Vue.
``` vue
<template>
        <div>
                <a-button @click="onClick">test__dirname</a-button>
        </div>
</template>

<script setup>
import loader from 'prismarine-chunk';
function onClick(){
        loader("1.18")
}
</script>
```
``` log
Uncaught ReferenceError ReferenceError: __dirname is not defined
    at node_modules/minecraft-data/data.js (\\wsl.localhost\Ubuntu\home\reinwd\ChunkPreview-front\node_modules\minecraft-data\data.js:1376:14)
    at __require (<censored ip:port>/node_modules/.vite/deps/chunk-HV2LENAN.js?v=76d1eddf:20:50)
    at node_modules/minecraft-data/index.js (\\wsl.localhost\Ubuntu\home\reinwd\ChunkPreview-front\node_modules\minecraft-data\index.js:134:14)
    at __require (<censored ip:port>/node_modules/.vite/deps/chunk-HV2LENAN.js?v=76d1eddf:20:50)
    at module.exports (\\wsl.localhost\Ubuntu\home\reinwd\ChunkPreview-front\node_modules\prismarine-registry\lib\index.js:4:22)
    at loader (\\wsl.localhost\Ubuntu\home\reinwd\ChunkPreview-front\node_modules\prismarine-chunk\src\index.js:36:60)
    at onClick (\\wsl.localhost\Ubuntu\home\reinwd\ChunkPreview-front\src\views\ChunkReader.vue:13:9)
    at callWithErrorHandling (\\wsl.localhost\Ubuntu\home\reinwd\ChunkPreview-front\node_modules\vue\node_modules\@vue\runtime-core\dist\runtime-core.esm-bundler.js:195:19)
    at callWithAsyncErrorHandling (\\wsl.localhost\Ubuntu\home\reinwd\ChunkPreview-front\node_modules\vue\node_modules\@vue\runtime-core\dist\runtime-core.esm-bundler.js:202:17)
    at emit (\\wsl.localhost\Ubuntu\home\reinwd\ChunkPreview-front\node_modules\vue\node_modules\@vue\runtime-core\dist\runtime-core.esm-bundler.js:715:5)
    at <anonymous> (\\wsl.localhost\Ubuntu\home\reinwd\ChunkPreview-front\node_modules\vue\node_modules\@vue\runtime-core\dist\runtime-core.esm-bundler.js:7803:45)
    at handleClick (\\wsl.localhost\Ubuntu\home\reinwd\ChunkPreview-front\node_modules\ant-design-vue\es\button\button.js:128:7)
    at callWithErrorHandling (\\wsl.localhost\Ubuntu\home\reinwd\ChunkPreview-front\node_modules\vue\node_modules\@vue\runtime-core\dist\runtime-core.esm-bundler.js:195:19)
    at callWithAsyncErrorHandling (\\wsl.localhost\Ubuntu\home\reinwd\ChunkPreview-front\node_modules\vue\node_modules\@vue\runtime-core\dist\runtime-core.esm-bundler.js:202:17)
    at invoker (\\wsl.localhost\Ubuntu\home\reinwd\ChunkPreview-front\node_modules\vue\node_modules\@vue\runtime-dom\dist\runtime-dom.esm-bundler.js:693:5)

```

Since `__dirname` is a feature of commonJS, I think it can be implemented in this plugin. May you give me some help contributing in this project about what to do? I'm not sure how to implement it.

中文 is also accepted.

**Comment by ReinWD** [comment]
and the process result is a very large chunk file.  It's also something not good in this case. I only want a small part of this module(version related), but prebuild generate a file with too much redundent code
![image](https://github.com/vite-plugin/vite-plugin-commonjs/assets/22649596/8af76208-d102-4222-b768-a01a11886f0b)

**Comment by yejimeiming** [comment]
Can you provide a minimal reproduction repo?
